name: Testing - renamed
on:
  # workflow_dispatch:
  #   branches:
  #     - qa
  #     - master
  #     - testing
  push:
    branches:
      - master

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - name: Test step
        run: echo "Testing"

# Test
