name: Testing
on:
  push:
    branches:
      - qa
      - master
      - testing
  repository_dispatch:
    types: [deployment-testing]

jobs:
  test-job:
    steps:
      - name: Test step
        run: echo "Testing"
